### ISSUE TITLE
Error on Startup but Doesn't Break Mod

### ISSUE THREAD

**Issue by Camawama** [GirafiStudios/BetterTitleScreen#14] opened 2020-01-31 05:58 UTC
I keep getting this error that is a bit annoying but doesn't really do much harm.
The screenshot is cut off but it's something about a resource. Sorry for the lack of info...

![Better Title SCreen Error](https://user-images.githubusercontent.com/43620900/73515886-6247b280-43bc-11ea-9a7f-23717e4867fa.png)

**Comment by GirafiStudios** [comment] 2020-01-31 12:59
Duplicate of https://github.com/GirafiStudios/BetterTitleScreen/issues/12
I'll release a new version with the fix for 1.15.2 (Will still be compatible with 1.15.1) later today.

**Closed by GirafiStudios** 2020-01-31 12:59 UTC
